package com.homepage;

import com.login.Login;
import com.register.conexion.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author harol
 */
public class Homepage extends javax.swing.JFrame {

    int xMouse2, yMouse2;
    boolean dark = false;

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        setIcons();
        hideOptions();
        login();
    }

    public void login() {
        usernametxt.setText(Conexion.name + " " + Conexion.last_name);
        correotxt.setText(Conexion.email);
        welcomeuser.setText("Welcome! " + Conexion.username);
    }

    public void getInfo() {
        Login a = new Login();

    }

    public void hideOptions() {
        panusersettings.setVisible(false);
        blackimg.setVisible(false);
        showemail.setVisible(false);
    }

    public void setIcons() {
        setImageLabel(labelimagen, "src/com/images/treehead.png");
        setImageLabel(jLabel2, "src/com/images/tr.png");
        setImageLabel(jLabel8, "src/com/images/download.png");
        setImageLabel(blackimgtxt, "src/com/images/blackworld.jpg");
    }

    public void setImageLabel(JLabel labelname, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();
    }

    public static void goLink(String link) {
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI uri = new java.net.URI(link);
                    desktop.browse(uri);
                } catch (URISyntaxException | IOException ex) {
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        exitbtn = new javax.swing.JPanel();
        exitbtntxt = new javax.swing.JLabel();
        panfavicon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panuserimage = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        welcomeuser = new javax.swing.JLabel();
        panusersettings = new javax.swing.JPanel();
        usernametxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        correotxt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        oscurotxt = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ignoreqtxt = new javax.swing.JLabel();
        log_outtxt = new javax.swing.JLabel();
        blackimg = new javax.swing.JPanel();
        blackimgtxt = new javax.swing.JLabel();
        panImagen = new javax.swing.JPanel();
        labelimagen = new javax.swing.JLabel();
        panRedes = new javax.swing.JPanel();
        emailtxt = new javax.swing.JLabel();
        githubtxt = new javax.swing.JLabel();
        linkedintxt = new javax.swing.JLabel();
        facebooktxt = new javax.swing.JLabel();
        panabouts = new javax.swing.JPanel();
        aboutxt = new javax.swing.JLabel();
        about_jta = new javax.swing.JTextArea();
        welcome_jta = new javax.swing.JTextArea();
        showemail = new javax.swing.JPanel();
        showemailtxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(241, 241, 241));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(255, 255, 255));

        exitbtntxt.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        exitbtntxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitbtntxt.setText("X");
        exitbtntxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtntxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitbtntxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitbtntxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtnLayout = new javax.swing.GroupLayout(exitbtn);
        exitbtn.setLayout(exitbtnLayout);
        exitbtnLayout.setHorizontalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitbtntxt, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );
        exitbtnLayout.setVerticalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitbtntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panfavicon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panfaviconLayout = new javax.swing.GroupLayout(panfavicon);
        panfavicon.setLayout(panfaviconLayout);
        panfaviconLayout.setHorizontalGroup(
            panfaviconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panfaviconLayout.setVerticalGroup(
            panfaviconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panfaviconLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panuserimage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBorder(new jroundborder.BorderRound());
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panuserimageLayout = new javax.swing.GroupLayout(panuserimage);
        panuserimage.setLayout(panuserimageLayout);
        panuserimageLayout.setHorizontalGroup(
            panuserimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panuserimageLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        panuserimageLayout.setVerticalGroup(
            panuserimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panuserimageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        welcomeuser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        welcomeuser.setText("Welcome");
        welcomeuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        welcomeuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                welcomeuserMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panfavicon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(welcomeuser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panuserimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panfavicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panuserimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeuser)
                .addGap(17, 17, 17))
        );

        bg.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        panusersettings.setBackground(new java.awt.Color(255, 255, 255));
        panusersettings.setPreferredSize(new java.awt.Dimension(150, 200));

        usernametxt.setText("user");

        correotxt.setText("mail@mail.com");

        oscurotxt.setText("Modo Oscuro");
        oscurotxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oscurotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                oscurotxtMousePressed(evt);
            }
        });

        ignoreqtxt.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        ignoreqtxt.setForeground(new java.awt.Color(153, 153, 153));
        ignoreqtxt.setText("DATOS DE USUARIO");

        log_outtxt.setText("Cerrar Sesion");
        log_outtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        log_outtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                log_outtxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panusersettingsLayout = new javax.swing.GroupLayout(panusersettings);
        panusersettings.setLayout(panusersettingsLayout);
        panusersettingsLayout.setHorizontalGroup(
            panusersettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panusersettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panusersettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1)
                    .addComponent(usernametxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correotxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(oscurotxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ignoreqtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(log_outtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panusersettingsLayout.setVerticalGroup(
            panusersettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panusersettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ignoreqtxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernametxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correotxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oscurotxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(log_outtxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(panusersettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 52, -1, 140));

        blackimg.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout blackimgLayout = new javax.swing.GroupLayout(blackimg);
        blackimg.setLayout(blackimgLayout);
        blackimgLayout.setHorizontalGroup(
            blackimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blackimgLayout.createSequentialGroup()
                .addComponent(blackimgtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        blackimgLayout.setVerticalGroup(
            blackimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blackimgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blackimgtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
        );

        bg.add(blackimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 420, 430));

        panImagen.setBackground(new java.awt.Color(241, 241, 241));

        labelimagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panImagenLayout = new javax.swing.GroupLayout(panImagen);
        panImagen.setLayout(panImagenLayout);
        panImagenLayout.setHorizontalGroup(
            panImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panImagenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(460, 460, 460))
        );
        panImagenLayout.setVerticalGroup(
            panImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panImagenLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(labelimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 420, 430));

        panRedes.setBackground(new java.awt.Color(241, 241, 241));

        emailtxt.setBackground(new java.awt.Color(102, 102, 102));
        emailtxt.setFont(new java.awt.Font("Open Sans Light", 1, 12)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(102, 102, 102));
        emailtxt.setText("Email");
        emailtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emailtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailtxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailtxtMousePressed(evt);
            }
        });

        githubtxt.setBackground(new java.awt.Color(102, 102, 102));
        githubtxt.setFont(new java.awt.Font("Open Sans Light", 1, 12)); // NOI18N
        githubtxt.setForeground(new java.awt.Color(102, 102, 102));
        githubtxt.setText("GitHub");
        githubtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        githubtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                githubtxtMousePressed(evt);
            }
        });

        linkedintxt.setBackground(new java.awt.Color(102, 102, 102));
        linkedintxt.setFont(new java.awt.Font("Open Sans Light", 1, 12)); // NOI18N
        linkedintxt.setForeground(new java.awt.Color(102, 102, 102));
        linkedintxt.setText("Linkedin");
        linkedintxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkedintxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                linkedintxtMousePressed(evt);
            }
        });

        facebooktxt.setBackground(new java.awt.Color(102, 102, 102));
        facebooktxt.setFont(new java.awt.Font("Open Sans Light", 1, 12)); // NOI18N
        facebooktxt.setForeground(new java.awt.Color(102, 102, 102));
        facebooktxt.setText("Facebook");
        facebooktxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facebooktxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                facebooktxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panRedesLayout = new javax.swing.GroupLayout(panRedes);
        panRedes.setLayout(panRedesLayout);
        panRedesLayout.setHorizontalGroup(
            panRedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRedesLayout.createSequentialGroup()
                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(facebooktxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(linkedintxt)
                .addGap(18, 18, 18)
                .addComponent(githubtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panRedesLayout.setVerticalGroup(
            panRedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRedesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panRedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(githubtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkedintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facebooktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bg.add(panRedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 230, 20));

        panabouts.setBackground(new java.awt.Color(241, 241, 241));

        aboutxt.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        aboutxt.setText("Acerca");

        about_jta.setEditable(false);
        about_jta.setBackground(new java.awt.Color(241, 241, 241));
        about_jta.setColumns(20);
        about_jta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        about_jta.setForeground(new java.awt.Color(102, 102, 102));
        about_jta.setRows(5);
        about_jta.setText("Cree Admin para entrenar Java & SQL, aplicando la \nLogica aprendida en cursos  estudiados de manera \nIndependiente como (Videos,Articulos,Libros,Foros)\nEmpeñando el rol de Estudio & Practica para mejorar. ");
        about_jta.setBorder(null);
        about_jta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        about_jta.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        about_jta.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout panaboutsLayout = new javax.swing.GroupLayout(panabouts);
        panabouts.setLayout(panaboutsLayout);
        panaboutsLayout.setHorizontalGroup(
            panaboutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panaboutsLayout.createSequentialGroup()
                .addGroup(panaboutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(about_jta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        panaboutsLayout.setVerticalGroup(
            panaboutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panaboutsLayout.createSequentialGroup()
                .addComponent(aboutxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(about_jta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        bg.add(panabouts, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 300, 110));

        welcome_jta.setEditable(false);
        welcome_jta.setBackground(new java.awt.Color(241, 241, 241));
        welcome_jta.setColumns(20);
        welcome_jta.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        welcome_jta.setRows(5);
        welcome_jta.setText("Bienvenido a Admin!\nUn proyecto con\nJava & MySQL.");
        welcome_jta.setBorder(null);
        welcome_jta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        welcome_jta.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        welcome_jta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bg.add(welcome_jta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 240, 110));

        showemail.setBackground(new java.awt.Color(255, 255, 255));

        showemailtxt.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        showemailtxt.setText("Jefeharold@gmail.com");

        javax.swing.GroupLayout showemailLayout = new javax.swing.GroupLayout(showemail);
        showemail.setLayout(showemailLayout);
        showemailLayout.setHorizontalGroup(
            showemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showemailLayout.createSequentialGroup()
                .addComponent(showemailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        showemailLayout.setVerticalGroup(
            showemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showemailtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        bg.add(showemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse2 = evt.getX();
        yMouse2 = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse2, y - yMouse2);
    }//GEN-LAST:event_HeaderMouseDragged

    private void exitbtntxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtntxtMouseEntered
        exitbtn.setBackground(Color.red);
        exitbtntxt.setForeground(Color.white);
    }//GEN-LAST:event_exitbtntxtMouseEntered

    private void exitbtntxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtntxtMouseExited

        exitbtntxt.setForeground(Color.black);

        if (dark == true) {
            exitbtn.setBackground(Color.darkGray);
        } else {
            exitbtn.setBackground(Color.white);
        }
    }//GEN-LAST:event_exitbtntxtMouseExited

    private void exitbtntxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtntxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitbtntxtMouseClicked

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        if (panusersettings.isVisible()) {
            panusersettings.setVisible(false);
        } else {
            panusersettings.setVisible(true);
        }
    }//GEN-LAST:event_jLabel8MousePressed

    private void oscurotxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oscurotxtMousePressed

        if (dark == false) {
            dark = true;
            oscurotxt.setText("Modo Claro");
            panImagen.setVisible(false);
            blackimg.setVisible(true);

            Header.setBackground(Color.DARK_GRAY);
            exitbtn.setBackground(Color.DARK_GRAY);
            panfavicon.setBackground(Color.DARK_GRAY);
            panuserimage.setBackground(Color.DARK_GRAY);
            panusersettings.setBackground(Color.darkGray);
            showemail.setBackground(Color.DARK_GRAY);

            bg.setBackground(Color.black);
            welcome_jta.setBackground(Color.black);
            about_jta.setBackground(Color.black);
            panRedes.setBackground(Color.black);
            panImagen.setBackground(Color.black);
            panabouts.setBackground(Color.black);

            usernametxt.setForeground(Color.white);
            correotxt.setForeground(Color.white);
            oscurotxt.setForeground(Color.white);
            log_outtxt.setForeground(Color.white);
            welcome_jta.setForeground(Color.white);
            about_jta.setForeground(Color.white);
            aboutxt.setForeground(Color.white);
            emailtxt.setForeground(Color.white);
            githubtxt.setForeground(Color.white);
            facebooktxt.setForeground(Color.white);
            linkedintxt.setForeground(Color.white);
            showemailtxt.setForeground(Color.white);
            welcomeuser.setForeground(Color.white);

        } else {
            dark = false;
            oscurotxt.setText("Modo Oscuro");
            panImagen.setVisible(true);
            blackimg.setVisible(false);

            Header.setBackground(Color.white);
            exitbtn.setBackground(Color.white);
            panfavicon.setBackground(Color.white);
            panuserimage.setBackground(Color.white);
            panusersettings.setBackground(Color.white);
            showemail.setBackground(Color.white);

            bg.setBackground(new Color(241, 241, 241));
            welcome_jta.setBackground(new Color(241, 241, 241));
            about_jta.setBackground(new Color(241, 241, 241));
            panRedes.setBackground(new Color(241, 241, 241));
            panImagen.setBackground(new Color(241, 241, 241));
            panabouts.setBackground(new Color(241, 241, 241));

            usernametxt.setForeground(Color.black);
            correotxt.setForeground(Color.black);
            oscurotxt.setForeground(Color.black);
            log_outtxt.setForeground(Color.black);
            welcome_jta.setForeground(Color.black);
            about_jta.setForeground(Color.black);
            aboutxt.setForeground(Color.black);
            emailtxt.setForeground(Color.black);
            githubtxt.setForeground(Color.black);
            facebooktxt.setForeground(Color.black);
            linkedintxt.setForeground(Color.black);
            showemailtxt.setForeground(Color.black);
            welcomeuser.setForeground(Color.black);
        }
    }//GEN-LAST:event_oscurotxtMousePressed

    private void log_outtxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_outtxtMousePressed
        Login a = new Login();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_log_outtxtMousePressed

    private void facebooktxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebooktxtMousePressed
        goLink("https://www.facebook.com/");
    }//GEN-LAST:event_facebooktxtMousePressed

    private void linkedintxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedintxtMousePressed
        goLink("https://www.linkedin.com/in/jefeharold/");
    }//GEN-LAST:event_linkedintxtMousePressed

    private void githubtxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_githubtxtMousePressed
        goLink("https://github.com/HaroId");
    }//GEN-LAST:event_githubtxtMousePressed

    private void emailtxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailtxtMousePressed
        showemail.setVisible(true);
    }//GEN-LAST:event_emailtxtMousePressed

    private void emailtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailtxtMouseExited
        showemail.setVisible(false);
    }//GEN-LAST:event_emailtxtMouseExited

    private void welcomeuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomeuserMousePressed
        if (panusersettings.isVisible()) {
            panusersettings.setVisible(false);
        } else {
            panusersettings.setVisible(true);
        }
    }//GEN-LAST:event_welcomeuserMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JTextArea about_jta;
    private javax.swing.JLabel aboutxt;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel blackimg;
    private javax.swing.JLabel blackimgtxt;
    private javax.swing.JLabel correotxt;
    private javax.swing.JLabel emailtxt;
    private javax.swing.JPanel exitbtn;
    private javax.swing.JLabel exitbtntxt;
    private javax.swing.JLabel facebooktxt;
    private javax.swing.JLabel githubtxt;
    private javax.swing.JLabel ignoreqtxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelimagen;
    private javax.swing.JLabel linkedintxt;
    private javax.swing.JLabel log_outtxt;
    private javax.swing.JLabel oscurotxt;
    private javax.swing.JPanel panImagen;
    private javax.swing.JPanel panRedes;
    private javax.swing.JPanel panabouts;
    private javax.swing.JPanel panfavicon;
    private javax.swing.JPanel panuserimage;
    private javax.swing.JPanel panusersettings;
    private javax.swing.JPanel showemail;
    private javax.swing.JLabel showemailtxt;
    private javax.swing.JLabel usernametxt;
    private javax.swing.JTextArea welcome_jta;
    private javax.swing.JLabel welcomeuser;
    // End of variables declaration//GEN-END:variables
}
